### ISSUE TITLE
Let the maven build fail, if a sass error occurs

### ISSUE THREAD

**Issue by larsgrefer** [darrinholst/sass-java#17]
Is it possible to let the maven build fail, if sass/compass finds syntax errors?

**Comment by darrinholst** [comment]
I'm guessing so, but off the top of my head I don't know for sure. We'd have to see what's returned [here](https://github.com/darrinholst/sass-java/blob/master/sass-java/src/main/java/com/darrinholst/sass_java/Compiler.java#L15)

**Comment by larsgrefer** [comment]
The ruby script returns Nil in both cases

**Comment by darrinholst** [comment]
Yeah, the `compile!` call in compass doesn't give you anything unfortunately. One option I can think of is to create another mojo called something like `check` that will look through the generated css for the error css that it generates (there may be some general purpose maven plugin that does something like this already). Or I supposed you could just check for errors after the `compiler.compile()` call in the existing `compile` mojo.

Probably the better option though would be to use libsass to do the compiling and deprecate this running ruby from java hack. That was the only stable thing available to me when I started this project. You might want to check out [libsass-maven-plugin](https://github.com/warmuuh/libsass-maven-plugin)
